### PR TITLE
Fix a bug causing the save method to interfere with other post types

### LINKED ISSUE #86: Error when publishing a CPT
When tryinh to publish a CPT from another plugin, I get the WordPress admin error
`The link you have followed has expired`
When I disable this plugin, I am able to publish as normal.
Have tested on a few environments and observed the same issue.

### PR DESCRIPTION
**Pull request by lukecarbis**
Resolves #86.

### CODE REVIEW

File: php/post-types/class-block-post.php [hunk 1]
```diff
@@ -621,6 +621,11 @@ public function save_block( $data ) {
 			return $data;
 		}
 
+		// Exits script if not the right post type.
```
Comment (rheinardkorf) [inline php/post-types/class-block-post.php:624]: That makes sense.

**Review by rheinardkorf — APPROVED** [review]
