### PR TITLE
Multiselect bug fixes

### LINKED ISSUE #195: Multi-Select Control: "Undefined index: items" from rest-api.php
Hello,

I tested the new Multi-Select control implementation. Unfortunately I receive an error 
**"Notice: Undefined index: items"** from the Rest API. (See full error output below!)

### Field config:

**Choices:**

```
news : News
info : Info
update : Update
```

**Default value:**

`news`

### Error output

```
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
{"rendered":"\r\n<h2>Just a box!<\/h2>\r\n\r\npre>\r\nbox-type:\r\narray(1) {\n  [0]=>\n  string(4) \"info\"\n}\n<\/pre>"}
```

### LINKED ISSUE #212: Field Multiselect - No selection returns array with element 0. (false)
Hi,

I created a multi-select field with 3 choices. If I don't select any of them, I nevertheless get an array with a first array element as result in the template output.  (See screen shot below)

**Expected behavior:** I receive an empty array.

**1. Don't select any select option:**

image

**2. Current output array in template including an empty element 0.**

image

**Used choices**

```
key-1-apple : Apple
key-2-pear : Pear
key-3-banana : Banana
```

### PR DESCRIPTION
**Pull request by lukecarbis**
Several bug fixes included here. Closes #195. Closes #212. Most important though is the bug where unsaved blocks weren't displaying the default values.

To test:

1. Create a new block containing:
    - A multi select with a default value
    - A Text control with a default value
2. Create a new post
3. Add the block, and click out of it immediately without changing any values
4. Add the block again, and set the values of both controls to empty
5. Add the block again, and set the values of both controls to something different

You should observe:

1. In the editor, the first block shows the default values
2. On the frontend, the first block shows the default values
3. In the editor, the second block shows empty values (an empty array for the multiselect)
4. On the frontend, the second block shows empty values (an empty array for the multiselect)
5. In the editor, the third block shows your custom values
6. On the frontend, the third block shows your custom values

### CODE REVIEW

File: js/blocks/controls/multiselect.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const BlockLabMultiselectControl = ( props, field, block ) => {
 
 	return (
 		<SelectControl
-			multiple="true"
+			multiple="multiple"
```
Comment (kienstra) [inline js/blocks/controls/multiselect.js:9]: This [document](https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/select-control/#multiple) seems to call for a boolean value for `multiple`. But you've looked at this for much longer than me, so I'll defer to your judgement. It looks like it was very intentional changing it.

File: php/blocks/class-loader.php [hunk 2]
```diff
@@ -203,6 +207,22 @@ public function render_block_template( $block, $attributes ) {
 			$type = array( 'preview', 'block' );
 		}
 
+		if ( 'edit' !== $context ) {
```
Comment (kienstra) [inline php/blocks/class-loader.php:210]: This is fine as is, but maybe it'd be simpler to have this as an `else` block of the conditional above:

```php
if ( 'edit' === $context ) {
	$type = array( 'preview', 'block' );
} else {
```

**Comment by kienstra** [comment]
**Approved**

Hi @lukecarbis,
This looks good, and all of your testing steps above went as expected.

Including when I set the values of the controls to empty:
mutli-select-empty-array

**Review by kienstra — APPROVED** [review]

File: js/blocks/controls/multiselect.js (hunk 1 above)
Comment (lukecarbis) [reply js/blocks/controls/multiselect.js:9]: There was a javascript Warning in the inspector suggesting to change it, due to the fact that although multiple="true" is valid, multiple="false" _isn't_, and could be confusing.
