### PR TITLE
Fix an issue with Classic Text fields in a repeater

### LINKED ISSUE #465: Classic Editor not interactive in Repeater in 2nd+ rows
Added a classic field to a repeater block and noticed that I could not interact with it from the second row onwards.
Video here on steps to reproduce.
https://d.pr/v/PjCSlG

### PR DESCRIPTION
**Pull request by kienstra**
As Rob [pointed out](https://github.com/getblocklab/block-lab/issues/465#issue-515808255), only the 1st Classic Text field in a repeater works.

This looks to be because all Classic Text controls in the same Repeater were using the same `editorId`. So this creates an `editorId` that's aware of the `rowIndex`.

### Steps to reproduce

1. In the Block Lab 'Edit Block' UI, add a Repeater control to a block, and add a Classic Text control to that
2. Create a new post, and add that block
3. The Classic Text control should work fine
4. Add another row to the Repeater
5. Expected: The Classic Text control in that 2nd row should work
6: Actual: It's not possible to edit that Classic Text control

Fixes #465

### CODE REVIEW

**Comment by kienstra** [comment]
Also, I tested that multiple Classic Text controls in the same block (not in a repeater) also work. They worked before and after this PR.

**Comment by kienstra** [comment]
**Request For Review**

Hi @RobStino and @lukecarbis,
Could you please review this? Hope you had a great weekend.

Thanks!

**Comment by jcrooke** [comment]
I can confirm this is now fixed 👍

**Comment by kienstra** [comment]
Nice, thanks for testing this!

**Comment by lukecarbis** [comment]
Code looks good to me, but I'm still having issues (slightly different that the issues I had before these changes).

https://fromsmash.com/fXP5zftmWr-c0

**Comment by kienstra** [comment]
Hi @lukecarbis,
OK, thanks for bringing that up. I'm a little sick today, so I probably won't have time to work on this today.

**Comment by kienstra** [comment]
Sorry I didn't get to this today. I'll work on it tomorrow if I'm not feeling worse, or Sunday (in the US) at the latest.

**Comment by kienstra** [comment]
Thanks for the good video of this. I could also reproduce this, but haven't figured out how to fix it.

I'll work on it more tomorrow (Sunday in the US).

**Comment by kienstra** [comment]
I'm working on this now. It's a tough one 😄

**Comment by kienstra** [comment]
I think the [commit above](https://github.com/getblocklab/block-lab/pull/466/commits/14532fcd6c3337796bc1023e3dd320573469c90b) fixes the [issue with disappearing Classic Text fields](https://github.com/getblocklab/block-lab/pull/466#issuecomment-550134215). But I need to test this a lot, as it has edits to `onChange()`, which every control uses to save its values.

File: js/blocks/components/fields.js [hunk 1]
```diff
@@ -59,33 +60,31 @@ const Fields = ( { fields, parentBlockProps, parentBlock, rowIndex } ) => {
 		 * the block's setAttributes property, so that the block can save the value.
 		 * This function is passed to the control so that the control can save the value,
 		 * depending on whether the control is in a repeater row or not.
+		 * This gets the latest parentAttributes by using select( 'core/block-editor' ),
+		 * as the parentBlockProps.attributes in the outer scope may be outdated.
```
Comment (kienstra) [inline js/blocks/components/fields.js:64]: It looks like the issue with the disappearing Classic Text fields was that it was using outdated `parentBlockProps.attributes`. So this gets them from the store.

File: js/blocks/components/fields.js [hunk 2]
```diff
@@ -59,33 +60,31 @@ const Fields = ( { fields, parentBlockProps, parentBlock, rowIndex } ) => {
...
 				// This is in a repeater row.
+				const attribute = attr[ field.parent ];
+				const defaultRows = [ {} ];
 				const rows = ( attribute && attribute.rows ) ? attribute.rows : defaultRows;
 
-				/*
-				 * Copy the rows array, so the change is recognized.
-				 * @see https://github.com/WordPress/gutenberg/issues/7016#issuecomment-396094836
-				 */
-				const rowsCopy = rows.slice();
```
Comment (kienstra) [inline js/blocks/components/fields.js:83]: It looks like this `rows.slice()` hack isn't needed anymore to allow saving repeater values. But more testing would be good.

File: js/blocks/components/fields.js [hunk 3]
```diff
@@ -118,9 +117,8 @@ const Fields = ( { fields, parentBlockProps, parentBlock, rowIndex } ) => {
 		const Control = getControl( field );
 
 		return !! Control && (
-			<div className={ getClassName( field ) }>
+			<div className={ getClassName( field ) } key={ `${ field.name }-control-${ rowIndex }` }>
```
Comment (kienstra) [inline js/blocks/components/fields.js:120]: This isn't related to the bug, but it prevents a console warning:

```
react-dom.js:539 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in Fields (created by FormControls)
    in FormControls (created by Edit)
    in div (created by Edit)
    in div (created by Edit)
    in Edit (created by edit)
```

**Comment by RobStino** [comment]
Hey @kienstra 
Just been testing this and the repeater work looks good. However classic text outside of the repeater is having an issue. :(
Testing included:
- new block
- Repeater field with a classic text subfield and a normal text subfield
- A normal non-repeater classic field and a number field

Video below of what I see:
https://d.pr/v/Hmwtnb

**Comment by kienstra** [comment]
**Request For Review**

Hi @lukecarbis,
Sorry for the delay. Could you please review this when you have a chance?

In my testing, saving all of the control types still works, both with and without a repeater.

Of course, before the upcoming release, we should do at least as much regression testing as usual.

Thanks, Luke!

File: js/blocks/components/fields.js (hunk 2 above)
Comment (kienstra) [reply js/blocks/components/fields.js:83]: I tested saving all of the controls in a repeater, and didn't see an issue.

**Comment by kienstra** [comment]
Hi @RobStino,
Thanks for testing this. Does the latest commit fix the issue for you?

I also saw the issue locall after watching your screencast, and it looks like that commit takes care of it.

**Comment by RobStino** [comment]
Hey @kienstra 
Thanks for that fix. Working correctly now.

**Comment by lukecarbis** [comment]
Looks good to me too. There's one other bug that I noticed: Re-ordering the classic fields inside a repeater doesn't work.

I'd be happy to open a new issue for that, if you wanted to merge this one, though.

File: js/blocks/components/fields.js (hunk 2 above)
Comment (lukecarbis) [reply js/blocks/components/fields.js:83]: I also tested, everything seemed to work.

**Review by lukecarbis — APPROVED** [review]

**Comment by kienstra** [comment]
>I'd be happy to open a new issue for that, if you wanted to merge this one, though.

Yeah, that'd be great if you could open another issue for that.
