### PR TITLE
Additional CSS Class Support

### LINKED ISSUE #253: Adding custom CSS causes error
I got a very similar issue that I can reproduce reliably.

How to reproduce:
1. Create any block in blocklab (even a super simple block with one text field, that just renders the text)
2. Add the block to a page
3. **Add a custom CSS class to the block** using the Gutenberg block settings menu (Block > Advanced)

2. Result
The block does not render in the editor, and throws "Error loading block: Invalid parameter(s): attributes". The error does not go away when you clear the custom CSS class.
The block does render OK on the frontend.

3. Additional information
- Wordpress 5.1.1
- Latest blocklab installed from wordpress repo

_Originally posted by @Artaud in https://github.com/getblocklab/block-lab/issues/244#issuecomment-473246294_

### PR DESCRIPTION
**Pull request by lukecarbis**
This is a simple fix, but comes with our first "dot tip".

**Testing the Advanced CSS Class**
Include the following in your template:
```
<p><?php block_field( 'className' );?></p>
<p><?php echo block_value( 'className' ); ?></p>
```

**Testing the DotTip**

1. You've probably disabled tips. It's easy to do. There's an [x] button included with all tips (including the default ones that show when you first use Gutenberg). Pressing this disables all tips permanently.

Screen Shot 2019-05-17 at 8 49 36 am

To re-enable tips you've got to clear your browser cookies, or even easier, type the following into your console:
```
wp.data.dispatch( 'core/nux' ).enableTips();
```

This time clear the default tips by pressing "See next tip" > "See next tip" > "See next tip" > "Got it".

2. Add a block. It's got to be a block that you have authored – we don't show the tip on blocks that you haven't authored, so that it doesn't show up for non-block-lab blocks, and it doesn't show for editors / clients who are using your blocks.

3. Click the block to show the edit interface, then in the sidebar, open the Advanced pane. You should see something like this:

Screen Shot 2019-05-17 at 8 48 06 am

Fixes #253.

Docs needed (@RobStino?)

### CODE REVIEW

File: js/blocks/loader/advanced.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+const { DotTip } = wp.nux;
+const { sprintf, __ } = wp.i18n;
+
+const inspectorControls = ( props, block ) => {
+	if ( '-1' === blockLab.authorBlocks.indexOf( block.name ) ) {
+		return;
+	}
+
+	const tip = sprintf(
+		__( 'The Additional CSS Class can be included in your block template with the %1$s field.', 'block-lab' ),
```
Comment (kienstra) [inline js/blocks/loader/advanced.js:13]: No need to change this, but `%s` is probably alright instead of `%1$s`

Comment (kienstra) [reply js/blocks/loader/advanced.js:13]: Good idea to have `'<code>className</code>'` in the second argument, so it can't change in translation.

File: js/blocks/loader/advanced.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+	return (
+		<InspectorAdvancedControls>
+			<DotTip tipId="block-lab/additional-css-class">
+				<p className="bl-dot-tip" dangerouslySetInnerHTML={{__html: tip}}></p>
+				<p className="bl-dot-tip read-more">
+					<a href="https://github.com/getblocklab/block-lab/wiki/7.-FAQ" target="_blank">{__( 'Read more', 'block-lab' )}</a>
+				</p>
+			</DotTip>
+		</InspectorAdvancedControls>
+	)
```
Comment (kienstra) [inline js/blocks/loader/advanced.js:26]: Should this `)` have a `;` after it?

File: php/blocks/class-loader.php [hunk 3]
```diff
@@ -100,6 +100,25 @@ public function editor_assets() {
 				$this->enqueue_block_styles( $block['name'], array( 'preview', 'block' ) );
 			}
 		}
+
+		// Used to conditionally show notices for blocks belonging to an author.
+		$author_blocks = get_posts(
+			array(
+				'author'         => get_current_user_id(),
```
Comment (kienstra) [inline php/blocks/class-loader.php:107]: Should this be `post_author` instead of `author`? Locally, only `post_author` got any posts.

File: php/blocks/class-loader.php [hunk 4]
```diff
@@ -100,6 +100,25 @@ public function editor_assets() {
...
+				'post_type'      => 'block_lab',
+				// We could use -1 here, but we'll limit it just in case somebody goes nuts with making custom blocks.
+				'posts_per_page' => 99,
+			)
+		);
+
+		$author_block_slugs = array_map(
```
Comment (kienstra) [inline php/blocks/class-loader.php]: This seemed to work locally, though `array_map()` worked as well:

```php
$author_block_slugs = wp_list_pluck( $author_blocks, 'post_name' );
```

File: php/blocks/class-loader.php [hunk 5]
```diff
@@ -100,6 +100,25 @@ public function editor_assets() {
 				$this->enqueue_block_styles( $block['name'], array( 'preview', 'block' ) );
 			}
 		}
+
+		// Used to conditionally show notices for blocks belonging to an author.
+		$author_blocks = get_posts(
+			array(
+				'author'         => get_current_user_id(),
+				'post_type'      => 'block_lab',
+				// We could use -1 here, but we'll limit it just in case somebody goes nuts with making custom blocks.
```
Comment (kienstra) [inline php/blocks/class-loader.php]: Sure, using `-1` could be dangerous.

**Review by kienstra — CHANGES_REQUESTED** [review]
**Looks Good**

Hi @lukecarbis,
This looks really good. The DotTip is a good UX.

Thanks for your great description here.

There are a few minor points here, but feel free to merge once you're satisfied.

block-lab-test

File: js/blocks/loader/advanced.js (hunk 1 above)
Comment (lukecarbis) [reply js/blocks/loader/advanced.js:13]: I always prefer specifying the placeholder order, due to this coding standard: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/e73a10e1c12ce07a12c3a8756efc54701458d23b/WordPress/Sniffs/WP/I18nSniff.php#L65

File: js/blocks/loader/advanced.js (hunk 2 above)
Comment (lukecarbis) [reply js/blocks/loader/advanced.js]: Doesn't need one, but I'll add one for consistency.

Comment (lukecarbis) [reply js/blocks/loader/advanced.js:26]: No, it doesn't need one. Choosing to keep it as is for consistency with `inspector.js` and `edit.js`

File: php/blocks/class-loader.php (hunk 4 above)
Comment (lukecarbis) [reply php/blocks/class-loader.php]: I always forget about `wp_list_pluck`. _Much_ nicer - thanks!

File: php/blocks/class-loader.php (hunk 3 above)
Comment (lukecarbis) [reply php/blocks/class-loader.php:107]: That's very weird. The `WP_Query` documentation says to use `author`. https://codex.wordpress.org/Class_Reference/WP_Query#Author_Parameters

Here's a gif of my testing using `author`. When I change one of my test blocks (the slug is `another-297-block`) so that it's authored by another user, it's not returned in the query. All my other blocks are.



Could you please check again?

File: php/blocks/class-loader.php (hunk 4 above)
Comment (lukecarbis) [reply php/blocks/class-loader.php]: Fixed in edc702e431aedddab45225732e52289461de8636

Comment (kienstra) [reply php/blocks/class-loader.php]: Yeah, functions like that hard to keep track of. I have to look them up every time I think about using them.

File: js/blocks/loader/advanced.js (hunk 1 above)
Comment (kienstra) [reply js/blocks/loader/advanced.js:13]: Ah, interesting

File: php/blocks/class-loader.php (hunk 3 above)
Comment (kienstra) [reply php/blocks/class-loader.php:107]: Sorry, it looks like I missed something. The `author` key looks to work fine now:

author-blocks-here

**Review by kienstra — APPROVED** [review]
**Approved**

Hi @lukecarbis,
Thanks for your responses and updates. I think this is ready to merge when you'd like.

**Comment by lukecarbis** [comment]
Thank you so much Ryan!

**Comment by kienstra** [comment]
Thank you, this is an important feature.
